### ISSUE TITLE
Problemi irrisolti

### ISSUE THREAD

**Issue by cheina97** [cheina97/Webotic_lab_2#4]
Scrivo quest'issue per annotare ciò che non sono riuscito a risolvere.
1. Non riesco a centrare il form della ricerca in alto nella navbar
2. Non riesco a far scomparire la barra laterale in maniera responsiva (e non capisco dove dovrebbe andare a finire quella finestra)
3. Non riesco ad allungare la div della colonna a sinistra (e di conseguenza il colore del background) fino al fondo della pagina
4. Quando premo il bottone in modalità responsive non riesco ad impedire che l'icona dell'utente finisca nella tendina appena aperta (ho risolto con un po' di javascript ma non è comunque bello/come dovrebbe essere)

Se qualcuno di voi ha avuto problemi simili può spiegarmi come avete risolto?
Grazie e buonanotte 😊

**Comment by cheina97** [comment]
ho risolto la questione dell'altezza della colonna grazie al codice di @alessandracomparetto  anche se continuo a non capire perchè la tua barra laerale sparisca

**Comment by alessandracomparetto** [comment]
Di quale barra laterale parli? verticale o orizzontale?
se ti riferisci a quella orizzontale, ho tolto qualche classe container nella section principale, in modo da evitare padding eccessivo (fuori dalla pagina per giunta)

"non capisco dove dovrebbe andare a finire quella finestra)" => quale finestra<

non so dirti molto per la tendina, a me non la apre mai, ho dei problemi con gli import di jquery o di popper, domani controllo meglio

**Comment by cheina97** [comment]
![image](https://user-images.githubusercontent.com/33266330/112069762-b1c2e200-8b6c-11eb-8843-1fc41944009e.png)
Intendo questa finestra, ma ora sono riuscito a risolvere e a farla sparire correttamente al ridimensionamento, grazie comunque 😃
Per quanto riguarda la tendina a me ora si apre senza problemi e include la barra di ricerca. Ciò che sbagliavo erano i riferimenti tra il bottone e il div con classe collapse (quello che deve contenere il form)

**Comment by cheina97** [comment]
Io chiudo l'issue se avete altri problemi apritene un'altra
